// <auto-generated />
using System;
using MODELS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MODELS.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20240721130011_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MODELS.Models.Customer", b =>
                {
                    b.Property<int>("Id_Customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Customer"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Customer");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("MODELS.Models.Product", b =>
                {
                    b.Property<int>("Id_Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Product"), 1L, 1);

                    b.Property<int>("Count_Products")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId_Customer")
                        .HasColumnType("int");

                    b.Property<int>("Id_Shop")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id_Product");

                    b.HasIndex("CustomerId_Customer");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("MODELS.Models.Shop", b =>
                {
                    b.Property<int>("Id_Shop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Shop"), 1L, 1);

                    b.Property<int?>("CustomerId_Customer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Shop");

                    b.HasIndex("CustomerId_Customer");

                    b.ToTable("Shop", (string)null);
                });

            modelBuilder.Entity("MODELS.Models.Product", b =>
                {
                    b.HasOne("MODELS.Models.Customer", null)
                        .WithMany("Cart")
                        .HasForeignKey("CustomerId_Customer");
                });

            modelBuilder.Entity("MODELS.Models.Shop", b =>
                {
                    b.HasOne("MODELS.Models.Customer", null)
                        .WithMany("Shops")
                        .HasForeignKey("CustomerId_Customer");
                });

            modelBuilder.Entity("MODELS.Models.Customer", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Shops");
                });
#pragma warning restore 612, 618
        }
    }
}
